version: '3.8'

services:
  localstack:
    build: ./localstack/
    command: sh -c "./localstack/scripts/invokeLambda.sh"
    environment:
      - SERVICES=lambda,iam,apigateway,sts,s3
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse}
      - LAMBDA_DOCKER_NETWORK=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp/localstack
      - KINESIS_PROVIDER=kinesalite
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/tmp/localstack/data
      - ./invokeLambda.sh:/docker-entrypoint-initaws.d/invokeLambda.sh
    networks:
      - localstack

volumes:
  localstack_data:
    name: localstack_data

networks:
 localstack:
    name: localstack